
hosts = {
"n1" => "192.168.69.10",
# "n2" => "192.168.69.11",
}

Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/bionic64"
 config.ssh.insert_key = false
 config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
     hosts.each do |name, ip|
     config.vm.define name do |machine|
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
       v.name = name
       v.memory = "1024"
      end
     end
 end
end
