
hosts = {
"n1" => "192.168.69.10",
"n2" => "192.168.69.11",
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.69.10"
 config.ssh.private_key_path = "~/.ssh/id_rsa"
 config.vm.provision "shell", inline: <<-SHELL
 cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

     hosts.each do |name, ip|
     config.vm.define name do |machine|
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
       v.name = name
       v.memory = "1024"
      end
     end
 end
end
